Fix Heroku deploy error
Error:

Enumerating objects: 148, done.

Counting objects: 100% (148/148), done.

Delta compression using up to 12 threads

Compressing objects: 100% (125/125), done.

Writing objects: 100% (128/128), 17.14 KiB | 1.43 MiB/s, done.

Total 128 (delta 78), reused 0 (delta 0), pack-reused 0

remote: Resolving deltas: 100% (78/78), completed with 13 local objects.

remote: Updated 41 paths from 0aa1d68

remote: Compressing source files... done.

remote: Building source:

remote:

remote: -----> Building on the Heroku-22 stack

remote: -----> Using buildpack: heroku/nodejs

remote: -----> Node.js app detected

remote:

remote: -----> Creating runtime environment

remote:

remote:        NPM_CONFIG_LOGLEVEL=error

remote:        NODE_VERBOSE=false

remote:        NODE_ENV=production

remote:        NODE_MODULES_CACHE=true

remote:

remote: -----> Installing binaries

remote:        engines.node (package.json):  20.2.0

remote:        engines.npm (package.json):   9.6.6

remote:

remote:        Resolving node version 20.2.0...

remote:        Downloading and installing node 20.2.0...

remote:        npm 9.6.6 already installed with node

remote:

remote: -----> Restoring cache

remote:        - npm cache

remote:

remote: -----> Installing dependencies

remote:        Installing node modules

remote:        npm ERR! code EUSAGE

remote:        npm ERR!

remote:        npm ERR! The `npm ci` command can only install with an existing package-lock.json or

remote:        npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or

remote:        npm ERR! later to generate a package-lock.json file, then try again.

remote:        npm ERR!

remote:        npm ERR! Clean install a project

remote:        npm ERR!

remote:        npm ERR! Usage:

remote:        npm ERR! npm ci

remote:        npm ERR!

remote:        npm ERR! Options:

remote:        npm ERR! [--install-strategy <hoisted|nested|shallow|linked>] [--legacy-bundling]

remote:        npm ERR! [--global-style] [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]

remote:        npm ERR! [--strict-peer-deps] [--no-package-lock] [--foreground-scripts]

remote:        npm ERR! [--ignore-scripts] [--no-audit] [--no-bin-links] [--no-fund] [--dry-run]

remote:        npm ERR! [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]

remote:        npm ERR! [-ws|--workspaces] [--include-workspace-root] [--install-links]

remote:        npm ERR!

remote:        npm ERR! aliases: clean-install, ic, install-clean, isntall-clean

remote:        npm ERR!

remote:        npm ERR! Run "npm help ci" for more info

remote:

remote:        npm ERR! A complete log of this run can be found in: /tmp/npmcache.11QlK/_logs/2023-10-24T02_34_31_454Z-debug-0.log

remote:

remote: -----> Build failed

remote:

remote:        We're sorry this build is failing! You can troubleshoot common issues here:

remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys

remote:

remote:        If you're stuck, please submit a ticket so we can help:

remote:        https://help.heroku.com/

remote:

remote:        Love,

remote:        Heroku

remote:

remote:  !     Push rejected, failed to compile Node.js app.

remote:

remote:  !     Push failed

remote:  !

remote:  ! ## Warning - The same version of this code has already been built: 632b653d5362aabd565319fcf6acb1a87bf7a5e1

remote:  !

remote:  ! We have detected that you have triggered a build from source code with version 632b653d5362aabd565319fcf6acb1a87bf7a5e1

remote:  ! at least twice. One common cause of this behavior is attempting to deploy code from a different branch.

remote:  !

remote:  ! If you are developing on a branch and deploying via git you must run:

remote:  !

remote:  !     git push heroku <branchname>:main

remote:  !

remote:  ! This article goes into details on the behavior:

remote:  !   https://devcenter.heroku.com/articles/duplicate-build-version

remote:

remote: Verifying deploy...

remote:

remote: !       Push rejected to whispering-meadow-38168.

remote:

To https://git.heroku.com/whispering-meadow-38168.git

! [remote rejected] main -> main (pre-receive hook declined)

error: failed to push some refs to 'https://git.heroku.com/whispering-meadow-38168.git'